translator:
  type: openai #openai
  openai_api_key: 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
layout:
  type: 'dit'
  device: 'cuda'

ocr:
  type: 'paddle'
  device: 'cuda'

font:
  type: 'simple'
